// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package test2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Test2ServiceClient is the client API for Test2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Test2ServiceClient interface {
	Test2(ctx context.Context, in *Test2Request, opts ...grpc.CallOption) (*Test2Response, error)
}

type test2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTest2ServiceClient(cc grpc.ClientConnInterface) Test2ServiceClient {
	return &test2ServiceClient{cc}
}

func (c *test2ServiceClient) Test2(ctx context.Context, in *Test2Request, opts ...grpc.CallOption) (*Test2Response, error) {
	out := new(Test2Response)
	err := c.cc.Invoke(ctx, "/test2.Test2Service/Test2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Test2ServiceServer is the server API for Test2Service service.
// All implementations must embed UnimplementedTest2ServiceServer
// for forward compatibility
type Test2ServiceServer interface {
	Test2(context.Context, *Test2Request) (*Test2Response, error)
	mustEmbedUnimplementedTest2ServiceServer()
}

// UnimplementedTest2ServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTest2ServiceServer struct {
}

func (UnimplementedTest2ServiceServer) Test2(context.Context, *Test2Request) (*Test2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test2 not implemented")
}
func (UnimplementedTest2ServiceServer) mustEmbedUnimplementedTest2ServiceServer() {}

// UnsafeTest2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Test2ServiceServer will
// result in compilation errors.
type UnsafeTest2ServiceServer interface {
	mustEmbedUnimplementedTest2ServiceServer()
}

func RegisterTest2ServiceServer(s grpc.ServiceRegistrar, srv Test2ServiceServer) {
	s.RegisterService(&Test2Service_ServiceDesc, srv)
}

func _Test2Service_Test2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Test2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Test2ServiceServer).Test2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test2.Test2Service/Test2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Test2ServiceServer).Test2(ctx, req.(*Test2Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Test2Service_ServiceDesc is the grpc.ServiceDesc for Test2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Test2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test2.Test2Service",
	HandlerType: (*Test2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test2",
			Handler:    _Test2Service_Test2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test2.proto",
}
